on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run-script check-format
    - run: npm run-script build
    - run: npm run-script lint
    - run: npm run-script coverage
    - uses: codecov/codecov-action@v3
